# Generated by Django 4.1 on 2023-05-26 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_compra', models.CharField(default='', max_length=10)),
                ('fecha', models.DateField()),
                ('monto', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes')),
            ],
            options={
                'db_table': 'Imagenes',
            },
        ),
        migrations.CreateModel(
            name='MovimientosAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoMovimiento', models.CharField(max_length=50)),
                ('Motivo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'MovimientosAlmacen',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'db_table': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('contraseña', models.CharField(default='', max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EPP.clientes')),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.FloatField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EPP.usuarios')),
            ],
            options={
                'db_table': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('descripcion', models.TextField()),
                ('cantidad', models.FloatField()),
                ('categoria', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='EPP.categorias')),
                ('imagen', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='EPP.imagenes')),
                ('prov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EPP.proveedores')),
            ],
            options={
                'db_table': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='detallesVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EPP.productos')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EPP.ventas')),
            ],
            options={
                'db_table': 'detallesVentas',
            },
        ),
        migrations.CreateModel(
            name='detallesCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EPP.compras')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EPP.productos')),
            ],
            options={
                'db_table': 'detallesCompras',
            },
        ),
        migrations.CreateModel(
            name='comprasAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.FloatField(default=0)),
                ('cantidad', models.FloatField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EPP.productos')),
                ('proveedores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EPP.proveedores')),
            ],
        ),
        migrations.AddField(
            model_name='compras',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='EPP.usuarios'),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EPP.productos')),
            ],
            options={
                'db_table': 'Carrito',
            },
        ),
    ]
