# Generated by Django 4.1 on 2023-05-26 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='categorias',
            table='Categorias',
        ),
        migrations.AlterModelTable(
            name='comprasadmin',
            table='comprasAdmin',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
