# Generated by Django 4.1.7 on 2023-03-02 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EPP', '0002_productos_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='contraseña',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='EPP.clientes'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='contrasenia',
            field=models.CharField(default='', max_length=50),
        ),
    ]
