# Generated by Django 4.1.7 on 2023-03-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPP', '0004_remove_compras_nombre_remove_usuarios_contrasenia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(upload_to='productos/'),
        ),
    ]
