# Generated by Django 4.1.7 on 2023-03-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPP', '0009_categorias_alter_productos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
    ]
