# Generated by Django 4.1.7 on 2023-03-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPP', '0011_categorias_alter_productos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
