# Generated by Django 4.1.7 on 2023-03-13 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EPP', '0013_imagenes_alter_productos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='EPP.imagenes'),
        ),
    ]
