# Generated by Django 4.1.7 on 2023-03-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPP', '0016_alter_proveedores_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='telefono',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
