# Generated by Django 4.1.7 on 2023-03-22 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EPP', '0017_alter_proveedores_email_alter_proveedores_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='comprasAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.FloatField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EPP.productos')),
                ('proveedores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EPP.proveedores')),
            ],
        ),
    ]
