# Generated by Django 4.1.7 on 2023-03-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPP', '0018_comprasadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasadmin',
            name='cantidad',
            field=models.FloatField(default=0),
        ),
    ]
