# Generated by Django 4.1 on 2023-05-26 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='Usuarios',
        ),
    ]
